INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('CASA BLANCA', 'CBLA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('CASA BLANCA', 'CBLA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('CASA BLANCA', 'CBLA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LOS SAUCES', 'SAUC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('PILARES', 'PILA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('U.H. TOLLOCAN 2', 'TOL2', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN JERÓNIMO', 'SJER', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN JERÓNIMO', 'SJER', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN JERÓNIMO', 'SJER', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN JERÓNIMO', 'SJER', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('C. FCO. I. MADERO', 'FCOI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('C. FCO. I. MADERO', 'FCOI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.S. TIZATLALLI', 'TIZA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('A.MOLINA E.', 'AMOL', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('BELLAVISTA', 'BELL', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LAS MARINAS', 'MARI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LA CAMPESINA', 'CAMP', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 2', 'IZC2', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 4', 'IZC4', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 1', 'IZC1', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 2', 'IZC2', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 3', 'IZC3', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI5', 'IZC5', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('IZCALLI 6', 'IZC6', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I. SAN FRANCISCO', 'ISFC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('U.H.L. CÁRDENAS', 'ULCA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('F. SAN CARLOS', 'SCAR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LOS CEDROS', 'CEDR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LA HORTALIZA', 'HORT', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('COAXUSTENCO', 'COAX', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. SAN MATEO', 'BSMA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I.F. SAN GABRIEL', 'ISGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I.F. SAN GABRIEL', 'ISGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I.F. SAN GABRIEL', 'ISGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I.F. SAN GABRIEL', 'ISGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('I.F. SAN GABRIEL', 'ISGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.F. COAXUSCO', 'SFCX', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('HÍPICO', 'HIPI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('HÍPICO', 'HIPI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN JAVIER', 'SJAV', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('ELECTRICISTAS', 'ELEC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('XINANTECATL', 'XINA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('MUNICIPAL', 'MUNI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('J.J. GALLARDO', 'JJGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('J.J. GALLARDO', 'JJGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('U.H.I. FABELA', 'UIFB', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('J.J. GALLARDO', 'JJGA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('U.H.J.F. ALBARRÁN', 'UJFA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('L.I. CAMPOS', 'LICA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('J.J. CANTÚ', 'JJCA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LAS MARGARITAS', 'MARG', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('A. MOLINA E.', 'AMOL', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LA PILITA', 'PILI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('A. MOLINA E.', 'AMOL', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('A. MOLINA E.', 'AMOL', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('C.L. CÁRDENAS', 'LCAR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('LA VIRGEN', 'VIRG', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. SAN MATEO', 'BSMA', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. STA CRUZ', 'BSCR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. STA CRUZ', 'BSCR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. SANTIAGUITO', 'BSNT', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. SAN MIGUEL', 'BSMI', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('B. ESPIRITU SANTO', 'BESP', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.J. PUEBLO NUEVO', 'SJOR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('OCOTITLÁN', 'OCOT', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.B. TLALTELULCO', 'SBAR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.B. TLALTELULCO', 'SBAR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('TOTOCUITLAPILCO', 'TOTO', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('TOTOCUITLAPILCO', 'TOTO', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('S.L. COACALCO', 'SLOR', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('TOTOCUITLAPILCO', 'TOTO', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN GASPAR', 'SGAS', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN GASPAR', 'SGAS', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN SEBASTIÁN', 'SSEB', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN LUCAS', 'SLUC', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('SAN SEBASTIÁN', 'SSEB', 'Metepec');
INSERT INTO colonias(nombre_colonia, abreviatura, municipio) VALUES('ÁLVARO OBREGÓN', 'ALVO', 'Metepec');

