DROP TABLE IF EXISTS datita;
CREATE TABLE IF NOT EXISTS datita(
    id_datita INT AUTO_INCREMENT PRIMARY KEY,
    apellido_p VARCHAR(20),
    apellido_m VARCHAR(20),
    nombres VARCHAR(20),
    zona VARCHAR(3),
    rg VARCHAR(4),
    seccion VARCHAR(4),
    casilla VARCHAR(2),
    pos VARCHAR(2),
    clave_e VARCHAR(20),
    tel VARCHAR(10)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MANJARREZ','ALBARRAN','DANIEL','9','RG26','2513','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALLEJO','SANCHEZ','FRANCISCO','5','RG13','2468','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','GASTELUM','ANGELIN','8','RG21','2528','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','GONZALEZ','JOAQUIN AL','5','RG13','2469','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PONCE','GONZALEZ','JESSICA BE','3','RG09','2506','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','ALCANTARA','OCTAVIO','3','RG08','2488','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','ALVAREZ','OLIVA','8','RG22','2535','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CUEVAS','MINOR','EDUARDO ERNE','8','RG22','2535','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARMONA','DIAZ','FERNANDA VER','8','RG22','2535','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BASTIDA','BASTIDA','VICTORIA','8','RG22','2535','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','APARICIO','ISRAEL','7','RG20','2527','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALENCIA','RODRIGUEZ','SANDRA','8','RG21','2537','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','PALMA','JUAN MANUEL','7','RG20','2526','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALDEZ','BONIFACIO','JUAN CAR','7','RG20','2525','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CORDOBA','SERVIN','CATALINA','4','RG10','2530','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','ESTRADA','JOEL JUA','4','RG10','2530','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','LOPEZ','MARINA','4','RG10','2530','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','SALGADO','ALEJANDRO','4','RG10','2530','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FERNANDEZ','MEJIA','OFELIA','4','RG11','2529','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVARADO','DORADO','EMMANUEL','4','RG11','2531','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALLEJO','GOMEZ','MILDRED','5','RG13','2468','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SALINAS','RODRIGUEZ','DANIEL','4','RG11','2534','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ORTIZ','GALINDO','PALOMA ESTE','4','RG11','2531','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHAPA','SILVA','ROGELIO','4','RG10','2530','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARDUÑO','CAMACHO','ROBERTA','4','RG10','2521','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','PLACIDO','MARIA GUA','4','RG10','2521','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CASTAÑEDA','RUBI','JANELLE LA','4','RG10','2530','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','ROMERO','KARINA','2','RG05','2538','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEDINA','VALENCIA','JORGE','2','RG05','2538','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CONTRERAS','HERNANDEZ','CHRIS','2','RG05','2538','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LUJANO','GRANADOS','JORGE LUI','2','RG05','2538','C4','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SUAREZ','VALENCIA','EMETERIA','2','RG05','2549','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','RAMIREZ','EMMANUEL','2','RG05','2538','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEDINA','RAMOS','BRAULIO GIL','2','RG05','2538','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ORTIZ','MEDINA','MARIA TERESA','2','RG05','2538','C5','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','VAZQUEZ','JUDITH','2','RG05','2538','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','ORTEGA','JESSICA','2','RG05','2538','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','MARTINEZ','PROCORO','2','RG06','2540','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CALDERON','VILLEGAS','ALEJAND','2','RG06','2540','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','CHAVEZ','EMILIO JUAN','2','RG04','2544','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','ROMERO','JESSICA GUA','2','RG05','2549','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONTELLANO','NERI','MAURICIO','2','RG05','2549','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','JIMENEZ','RODRIGO','2','RG07','2543','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HIDALGO','CASTAÑEDA','MARIA G','4','RG10','2530','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','CHICHO','JORGE MA','4','RG10','2520','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','HERNANDEZ','PALOMA','6','RG15','2490','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALDEZ','XX','NEREIDA','5','RG14','2471','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','HERNANDEZ','LEONARDO','7','RG19','2501','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('COYOLI','TRUJILLO','CINTHIA L','7','RG19','2501','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','CHAVEZ','RAMON','1','RG01','2486','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MENESES','RAMIREZ','KARLA','1','RG03','2480','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','REYES','BENJAMIN','1','RG02','2485','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','REYES','BELEM','5','RG13','2469','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','DIAZ','ADRIANA','5','RG13','2468','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','CALZADA','RENE','5','RG13','2469','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARIN','DELGADO','FRANCISCO J','5','RG12','2464','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','ESQUIVEL','ROSA ISEL','5','RG12','2464','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','GARDUÑO','MARTHA L','5','RG12','2464','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','RODRIGUEZ','DIEGO','5','RG12','2464','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','RODRIGUEZ','GUADAL','5','RG12','2464','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','LARA','JOSE IGNACIO','5','RG12','2464','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('XX','CRUZ','JOVITA','5','RG13','2466','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PONCE','RAMIREZ','JORGE','9','RG26','2532','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DE','LEON','ARZATE DIMAS','5','RG13','2466','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','BADILLO','LETICIA','5','RG13','2467','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ANAYA','TAPIA','ARIANA','5','RG13','2467','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','SUSANO','COLUMBA','5','RG13','2468','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALLEJO','GOMEZ','MARTHA EULA','5','RG13','2467','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SEGUNDO','TIBURCIO','GLORIA','5','RG13','2467','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOLIS','CARBALLO','RUBEN','5','RG13','2469','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','SOTO','RENE','2','RG07','2543','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','ACEVEDO','ERICK','5','RG13','2469','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHICHO','GOMEZ','JAQUELINE RO','5','RG13','2469','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','GONZALEZ','MERCED','5','RG14','2471','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOLIS','CRUZ','JAVIER','5','RG14','2474','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','LOPEZ','LUCIA','5','RG14','2474','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARDUÑO','PINEDA','CLAUDIA','9','RG24','2470','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MOLINA','GONZALEZ','JESUS ENR','9','RG24','2470','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVARADO','VELAZQUEZ','MARIA','5','RG12','2475','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARIN','DELGADO','MARIA DEL C','5','RG12','2475','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','PEREZ','EDITH IVET','5','RG12','2475','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BENITEZ','RAMOS','MARTHA','1','RG02','2479','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','GALINDO','ANA GABRIE','1','RG03','2480','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FRESNEDO','ROBLES','NATALIA','1','RG03','2480','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVAREZ','DE LA ROSA','ISELA','1','RG03','2480','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','CUELLAR','RAQUEL','5','RG01','2486','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PADILLA','CAJERO','NORMA EVEL','1','RG02','2485','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ANGELES','URIBE','SILVIA ALEJ','1','RG02','2485','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONTES DE OCA','MEDINA','EDGA','5','RG01','2486','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','DE LA PORTILLA','ANA','2','RG04','2544','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONTES DE OCA','MEDINA','EVEL','1','RG01','2486','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','HERNANDEZ','MIGUEL AN','3','RG08','2487','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LUNA','SANCHEZ','CLAUDIA MARI','3','RG08','2487','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','PONCE','ANGELA VALER','3','RG08','2489','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','VAZQUEZ','MIRIAM ALE','1','RG03','2480','C6','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','ROMERO','JULIO CE','6','RG15','2490','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORTORIELLO','ZAVALA','SANDRA','6','RG15','2490','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','MUÑOZ','ELIZABETH','2','RG07','2545','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','ALMAZAN','JORGE','6','RG16','2491','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','ALMAZAN','LUIS','6','RG16','2491','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JARDON','GUADARRAMA','LEONARD','2','RG07','2543','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','ALMAZAN','MARIA TERESA','6','RG16','2491','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('QUIROS','CUARTO','KARLA ESTEF','7','RG18','2498','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','MARURI','MARIA GU','7','RG18','2498','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','CONTRERAS','ANGEL A','7','RG18','2498','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CONTRERAS','ARRIAGA','AURORA','7','RG18','2498','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','MORALES','ROSALIO','7','RG18','2498','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','PLATA','ADRIANA LISS','7','RG18','2498','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARQUEZ','ALCAZAR','DULCE CAR','7','RG18','2498','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MENDIETA','ALVAREZ','FABIOLA','7','RG18','2498','C3','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOTO','SANCHEZ','MARY SOL','7','RG18','2499','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('NOGUEDA','OCAÑA','HIPOLITO DA','7','RG18','2499','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MICHEL','GOMEZ','CARMEN LETIC','7','RG19','2500','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','LARA','HEBER ISAAC','7','RG19','2501','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('OLVERA','RAMOS','MARIA GUADAL','7','RG19','2501','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALLEJO','GOMEZ','MARIA ESTHE','7','RG18','2503','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TOLEDO','VALLEJO','DAFNE ANGE','7','RG18','2503','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','CLIMACO','CLAUDIA','7','RG18','2503','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HURTADO','MALVAEZ','VERONICA','7','RG18','2503','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BARBOSA','LOPEZ','JORGE ARTUR','7','RG18','2499','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','VILCHIS','LUIS ANGEL','7','RG18','2499','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUTIERREZ','HERNANDEZ','PATRI','6','RG17','2504','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONTES DE OCA','VAZQUEZ','BRY','6','RG16','2505','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PONCE','GONZALEZ','ROCIO','3','RG09','2506','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JIMENEZ','ARCHUNDIA','MARIA D','3','RG08','2507','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CONTRERAS','RAMIREZ','LIZBETH','3','RG08','2507','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARIAS','LOPEZ','RENE SALOMON','3','RG08','2509','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARIAS','URBINA','ALEX OSTOK','3','RG08','2509','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARIAS','URBINA','BRITZI MICHE','3','RG08','2509','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('AGUILAR','FLORENCIO','ERIKA A','3','RG08','2509','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MALVAEZ','RIOS','ANDREA','9','RG24','2512','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','CHACON','EMMA AIDA','9','RG24','2512','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONTAÑEZ','TAPIA','GUADALUPE','9','RG24','2512','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARIZMENDI','ITURBIDE','JOSSEL','3','RG09','2518','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ITURBE','FASSEN','MIGUEL ANGE','3','RG09','2518','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','ROGEL','SUSANA','3','RG09','2518','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHICHO','GARCIA','NORMA','4','RG10','2520','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','HERNANDEZ','LETICIA J','4','RG10','2520','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','MEJIA','ENRIQUE','4','RG10','2520','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','VALDES','ROCIO','4','RG10','2520','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('EREYVA','MARILES','ELIZABETH','2','RG05','2538','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GRANADOS','CASTAÑEDA','SUSANA','2','RG05','2538','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JARDON','PERALTA','OSCAR','2','RG05','2549','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORAN','MORAN','MARCELO','3','RG09','2518','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESTRADA','COLIN','EDUARDO','3','RG08','2489','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ABAD','CASTILLO','ERICKA AMAI','3','RG09','2506','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PIÑON','QUIROZ','MARISELA','7','RG18','2499','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SILVA','CAMPOS','SANDRA LUZ','7','RG20','2524','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LARA','CABALLERO','RODRIGO','3','RG08','2488','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESTRADA','CHAVEZ','INGRID','3','RG08','2488','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','LOPEZ','MIGUEL DI','1','RG02','2485','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BARRAGAN','NEGRETE','LUIS ENR','1','RG03','2480','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PICHARDO','PICHARDO','GUILLER','2','RG04','2533','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','PEREZ','BALTAZAR','2','RG05','2549','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','JIMENEZ','FELIPE','7','RG20','2525','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','DAVILA','LUCIANO','7','RG20','2526','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','PEREZ','FABIAN','2','RG04','2544','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRATOS','BOBADILLA','LORENA','2','RG04','2544','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','PEREZ','TOMAS','2','RG04','2544','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','BERNAL','DANIELA','2','RG05','2549','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEREZ','MERCADO','AXEL MICHEL','5','RG12','2465','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','BRIZ','ANA MARGAR','5','RG12','2465','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILLASEN?OR','CORTES','KENIA','5','RG12','2465','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','MENDEZ','CYNTHIA ELIZ','5','RG12','2465','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOLANO','GUADARRAMA','MARIELA','8','RG21','2537','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','PEREZ','ARMANDO A','2','RG07','2545','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SILVA','CAPETILLO','ALMA GUAD','5','RG13','2466','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RUIZ','SALINAS','LUIS EDOARDO','5','RG13','2466','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARREGUIN','GONZALEZ','ANA LAU','7','RG19','2500','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SALINAS','ESTRADA','EDWIN ABR','5','RG13','2466','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','GALVAN','ANA KAREN','5','RG13','2466','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SUAREZ','VALENCIA','EMETERIA','2','RG05','2549','C3','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','VAZQUEZ','JESICA BEA','1','RG03','2480','C5','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','ALVARADO','ARACELI','1','RG01','2477','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','HERNANDEZ','JOSE LUI','1','RG01','2477','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RIVERA','BERNAL','ANGEL','1','RG01','2478','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ANAYA','GUTIERREZ','ELISA MAR','6','RG15','2490','C5','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FERNANDEZ','CARRILLO','CLEOTI','9','RG24','2512','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','MIGUEL','SONIA ADRIANA','9','RG26','2513','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','SALGADO','JONATHAN','9','RG24','2512','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','ARAIZA','PAOLA','7','RG19','2502','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARAIZA','BELMARES','ANABELL D','7','RG19','2502','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('XX','CRUZ','MARIA DE LOURDES','1','RG02','2479','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEREZ','GARCIA','JONATHAN IVA','3','RG08','2487','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','RUBIO','CARLOS ARTURO','8','RG21','2537','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DÍAZ','ZERMEÑO','JOB WILLIAMS','6','RG15','2490','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GALLEGOS','CARRILLO','NADIA Y','8','RG23','2547','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','ORTEGA','MARCO ANTONIO','4','RG11','2529','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','CASTILLO','JORGE','4','RG11','2534','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','SAMANO','IVON','4','RG11','2534','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DOMINGUEZ','SANCHEZ','MARIA I','6','RG15','2490','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GELDIS','SOTO','CECILIA','6','RG15','2490','C6','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','LOPEZ','JESUS','6','RG15','2490','C7','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','VELAZQUEZ','MARIA E','6','RG15','2490','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILCHIS','OROZCO','MARINA','6','RG15','2490','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ZAMORA','RAMÍREZ','ABELARDO','6','RG15','2490','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','GOMEZ','MARCIAL HORA','6','RG16','2491','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JUAREZ','VAZQUEZ','CESAR MAUR','6','RG16','2491','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','LOYOLA','ANGEL FERN','6','RG16','2505','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','SANCHEZ','ARLETTE','6','RG17','2494','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','ARMAS','LEONEL ALE','7','RG19','2523','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOTO','RUBIO','JESUS ANTONIO','7','RG20','2524','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','RIVERA','GELOS','8','RG22','2539','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PICHARDO','JAIMES','PATRICIA','8','RG22','2539','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','LOPEZ','LAURA ANGELICA','9','RG26','2513','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RICO','LOPEZ','SALVADOR','9','RG26','2513','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','PADILLA','DENISSE','1','RG03','2480','C6','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','PONCE','DE LEON NAZA','2','RG04','2533','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','RAMIREZ','EMMANUEL','2','RG05','2549','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','ELIAS','JUAN CARLO','9','RG25','2510','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VELAZQUEZ','MENDEZ','PILAR AL','9','RG25','2510','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','SANCHEZ','SANDRA','9','RG25','2510','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RIOS','LARA','OMAR','9','RG25','2510','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','CAMACHO','AIDE','9','RG25','2511','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ELIAS','GUTIERREZ','CLAUDIO','8','RG22','2539','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CANO','GARATACHIA','ANGELA','9','RG25','2511','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MANJARREZ','GONZALEZ','CINDY','8','RG21','2528','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','RAMOS','OSVALDO','7','RG20','2525','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','MORALES','HUGO','6','RG15','2490','C6','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','SERRANO','AGUSTIN','6','RG15','2490','C6','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','LUNA','EDWIN JOVANI','6','RG15','2490','C5','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','GARCIA','LILIA PAT','6','RG15','2490','C5','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CERVANTES','TERRON','DIANA GE','6','RG15','2490','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARCOS','DE LEON','YELITZA AIM','5','RG13','2466','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BAUTISTA','CARDENAS','ZENAID','7','RG20','2525','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BARRERA','GARCIA','QUINTIN','4','RG10','2521','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('UCO','JIMENEZ','JESUS','9','RG24','2512','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANABRIA','MACEDO','EMMANUEL','9','RG24','2512','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LIMON','DOMINGUEZ','JUAN CARL','9','RG25','2515','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CORTES','MEDINA','ELIAS','9','RG25','2515','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','BERNAL','BELEN','9','RG26','2513','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('AGUILAR','LARA','MARIA REFUGI','9','RG26','2513','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','ORTEGA','ROSALVA','9','RG25','2515','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','MESSILLAS','IVAN','9','RG25','2515','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','AGUILAR','MARIAN','9','RG25','2515','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','ORTEGA','MARIA GUADALU','9','RG25','2515','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROJAS','PEREZ','JORGE ALBERTO','9','RG26','2513','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','MARIN','HECTOR DA','9','RG26','2513','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANTA MARIA','PEREZ','DULCE','9','RG25','2516','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILCHIS','ONOFRE','ARTURO','9','RG25','2516','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROSALES','ARROYO','LIDIA YATZ','2','RG05','2538','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROSAS','ROBLES','KARLA YENNY','9','RG26','2513','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CORONA','ARZATE','SERGIO','9','RG26','2513','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','RUIZ','LUIS ALBERTO','9','RG26','2513','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEDINA','DEGOLLADO','MAYAREL','9','RG26','2532','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANTA','ANA','JIMENES BRENDA','5','RG14','2473','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARILLO','DEGOLLADO','ALBA NA','9','RG26','2514','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOAIZA','NAVA','RODRIGO','1','RG02','2485','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','CARLOS VER','9','RG26','2513','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEÑA','ECHEGARAY','MA DE LOUR','4','RG10','2520','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DEGOLLADO','SALAS','OLGA LIDI','9','RG26','2532','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GALINDO','REYES','DANIEL','9','RG26','2513','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','GOMEZ','OCTAVIO','9','RG26','2513','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','ALEJANDRA','9','RG26','2514','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','NADIA ELIZ','9','RG26','2514','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','SAMUEL','9','RG26','2514','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VENTURA','MELITON','SUSANA','2','RG04','2533','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CEDILLO','MIRA','MA DEL PILAR','2','RG05','2538','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEREZ','LIEVANA','HUMBERTO','1','RG03','2480','C7','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','SERRANO','DIANA','6','RG15','2490','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RANGEL','ROJAS','LAURA MARCEL','2','RG06','2542','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TAHUILAN','CALLOS','ELIZABETH','6','RG15','2490','BA','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TREJO','MARTINEZ','ANGELICA','2','RG06','2542','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','ZAMORA','PAMELA S','2','RG06','2542','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VEGA','SANCHEZ','ANA MARIA','6','RG16','2491','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','GONZALEZ','ALDO A','4','RG11','2529','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SUAREZ','GARDUÑO','CRISTHIAN','6','RG16','2504','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORQUECHO','BASTIDA','DANIELA','8','RG22','2535','C1','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERAS','GARCIA','ELIA','9','RG26','2513','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MAYA','BENITEZ','BIBIANA ISAB','9','RG26','2532','C3','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARRILLO','GONZALEZ','DANIEL','6','RG15','2490','C2','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESTEVEZ','BONILLA','JOSE RAFA','1','RG01','2486','BA','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARRILLO','MEJIA','LESLIE DAN','1','RG02','2481','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESPINOSA','ESPINOSA','ANTONIA','2','RG04','2544','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('AYALA','CALDERON','JOSE GUADA','9','RG26','2532','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','HERNANDEZ','ERICK','6','RG15','2490','C7','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','ORTEGA','ELVIA','6','RG15','2490','C7','S2','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BAUTISTA','CARBAJAL','SONIA','7','RG20','2525','C1','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','LEON','JIMMY ERIC','6','RG15','2490','C7','S3','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ZEPEDA','GONZALES','MARGARITA','6','RG15','2490','C7','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','LEON','ADRIANA','6','RG15','2490','C7','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','ROMERO','MARGARITO','9','RG26','2513','C4','PR','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESPINOZA','PALOMINO','PAOLA A','6','RG15','2490','C7','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROCHA','LEON','HENRY JESUS','6','RG15','2490','C7','S2','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','BALTAZAR','ALICIA','6','RG15','2490','C7','S3','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','GONZALEZ','JUANA','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','RUIZ','ARELI JAZMIN','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VELAZQUEZ','CAMACHO','ADALID','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','AYALA','CLEOTILDE','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BARRERA','SANCHEZ','BRUNO','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILLA','JIMENEZ','ANA ELIN','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONDRAGON','NIEVES','GABINO','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MALVAEZ','GOMEZ','JOSE MANUEL','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORQUECHO','ESCOBAR','RAUL','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILVHIS','VILLASETIN','EFREN','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','HERNANDEZ','BRYAN A','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','PADILLA','NORMA ANGEL','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTIN','DEL CAMPO','SAVEDRA','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALENCIA','LOPEZ','GREGORY','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PLACIDO','CAÑAS','JORGE','1','RG01','2477','C2','S1','','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','GOMEZ','OCTAVIO','8','RG22','2539','C6','S1','GNGMOC75091609H600','7226693798');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ZETINA','ROBLES','FELIPE','8','RG22','2539','C6','S1','ZTRBFL77082315H100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GALINDO','REYES','DANIEL','8','RG22','2539','C6','S1','GLRYDN94063015H800','7224444542');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROJAS','ESPARZA','RAMON','8','RG22','2539','C6','S1','RJESRM52082915H100','7222112723');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOAIZA','NAVA','RODRIGO','8','RG22','2539','C6','S1','LZNVRD80080615H400','7225679551');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANABRIA','VELAZQUEZ','HECTOR','8','RG22','2535','C3','S1','SNVLHC72020609H601','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','PALAFOX','ENRIQUE','8','RG22','2535','C3','S1','LPPLEN67012421H600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VILLA','MONDRAGON','MIGUEL AN','8','RG22','2535','C3','S1','VLMNMG41020815H800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ORTIZ','SANCHEZ','ADILENE YOZ','8','RG22','2535','C3','S1','ORSNAD90082415M500','7228011353');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VELEZ','ALVAREZ','MARIA DE JE','8','RG22','2535','C3','S1','VLALJS58110715M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','FLORES','ANA MARIA','8','RG22','2535','C3','S1','LPFLAN45112615M500','7293840672');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALERIO','RAMIREZ','FRANCISCO','8','RG22','2535','C3','S1','VLRMFR35082430H800','7293840672');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CASTRO','ARELLANO','NOEL','8','RG22','2535','C3','S1','CSARNL64082409H401','7223913578');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','PEREZ','MARIA LUISA','8','RG21','2528','C3','S1','VZPRLS02020915M000','7227976477');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','PEREZ','MARIA MONSE','8','RG21','2528','C3','S1','VZPRMN00033115M600','7226831174');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARURE','MENDOZA','DAVID','8','RG23','2548','C4','S1','MRMNDV72121515H400','7225712507');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARURE','SANCHEZ','ALAN ALDAI','8','RG23','2548','C4','S1','MRSNAL97020815H900','7223155778');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MENDOZA','CONTRERAS','YOLANDA','8','RG23','2548','C4','S1','MNCNYL38110915M101','7221203514');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','ARCOS','LILIBET','8','RG23','2548','C4','S1','SNARLL72110615M100','7224292776');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARCOS','MANUEL','JAVIER','8','RG23','2548','C4','S1','JVARMN80112312H200','5531458949');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','ALEJANDRA','8','RG23','2548','C4','S1','RMPZAL89032315M500','7225573946');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','CARLOS VER','8','RG23','2548','C4','S1','RMPZCR98041215H400','7292876701');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PAZARON','NADIA ELIZ','8','RG23','2548','C4','S1','RMPZND00011315M600','7222018544');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SALAZAR','GONZALEZ','NICOLAR','2','RG05','2549','C3','S1','SLGNNO75050915H501','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANDOVAL','MEJIA','JACINTO SA','5','RG12','2464','BA','PR','SNMJJC80091115H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANDOVAL','MEJIA','ANA ELIA','5','RG12','2464','BA','PR','SNMJAN78032009M802','7225246788');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALANIZ','RODRIGUEZ','ALBERTO','9','RG25','2510','C1','S1','ALRDAL53080715H500','7292486457');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CASTILLO','RUIZ','BRYAN AXEL','5','RG12','2464','BA','PR','CSRZBR01062615H500','7227698784');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CORTES','RINCON','AMELIA','9','RG25','2510','C1','S1','CRRNAM53010515M300','7223985870');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SEGURA','AYALA','LILIA','5','RG12','2464','BA','PR','SGAYLL65060811M501','7221802826');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FENTANEZ','CRUZ','ESTHER','9','RG25','2510','C1','S1','FNCRES57101320M400','7222066108');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FERNANDEZ','DEGOLLADO','EDNA','9','RG25','2510','C1','S1','FRDGED73021315M400','7221694346');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('URBINA','TORRES','JAIR ISMAEL','5','RG12','2464','BA','PR','URTRJR88010415H600','7224528611');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TAPIA','MANZUR','KRISTELLE','9','RG25','2510','C1','S1','TPMNKR96042715M200','7291111054');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TAPIA','MANZUR','KATE','9','RG25','2510','C1','S1','TPMNKT00012415M900','7221184515');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','ROMERO','MARIO MIGU','9','RG25','2510','C1','S1','CMRMVR82011915H100','7228880431');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','PIÑA','MARIA DOLORES','5','RG12','2464','BA','PR','RMPIMA69072215M001','7223635480');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROMERO','DE LA ROSA','APOLONI','9','RG25','2510','C1','S1','RMRSAPB61020515M30','7228880431');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROSSANO','MONDRAGON','ADRIANA','5','RG12','2464','BA','PR','RSMNAR81012115M800','7226265508');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LARA','CONTRERAS','LIZETTE MI','9','RG25','2510','C1','S1','LRCNLZ82020315M200','5583350239');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','MEJIA','EDGAR','5','RG12','2464','BA','PR','GRMJED84061515H100','7221552021');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PONCE','ZAMORA','ESTHELA MARG','9','RG25','2510','C1','S1','PNZMES69051515M500','7227488313');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','FERNANDEZ','ALEJAN','5','RG12','2464','BA','PR','GMFRAL86031815M600','7221565087');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARRILLO','GARCIA','JOSE DANI','5','RG12','2464','BA','PR','CRGRDN93121115H500','7224449698');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('POPOCA','FLORES','ENRIQUE','9','RG25','2510','C1','S1','PPFLEM64012115H100','7228939789');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','JIMENEZ','ALONDRA IR','5','RG12','2464','BA','PR','GRJMAN00062115M200','7295270883');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PICHARDO','PAVON','JAIME RICA','9','RG25','2510','C1','S1','PCPVJM75121415H601','7225043564');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JIMENEZ','FERNANDEZ','JOVANA','5','RG12','2464','BA','PR','JMHRJV01012815M100','7291430650');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VELAZQUEZ','MENDEZ','JHOANA','5','RG12','2464','BA','PR','VLMNJH00062115M400','7223685121');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MIRANDA','ROMO','PALOMA','5','RG12','2464','BA','PR','MRRMPL76051015M900','7225692641');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SILVA','CAMPOS','SERGIO ALBER','5','RG12','2464','BA','PR','SLCMSR82082315H700','7291501925');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LAVANDEROS','SEGURA','JUAN','9','RG25','2510','C1','S1','LVSGJN67062409','7222456842');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALADINO','PIÑA','MARIA DE JES','5','RG12','2464','BA','PR','ALPIPR66101615M000','7221571667');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','HERNANDEZ','MARCO AGUS','9','RG25','2510','C1','S1','DZHRMR82121615H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','ALANIS','JACQUELINE','5','RG12','2464','BA','PR','LPALJC79100615M100','7222061628');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','ITURBE','RODOLFO','9','RG25','2510','C1','S1','ESITRD48060915H200','7224003998');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEÑA','MANCILLA','MARIA DE JE','5','RG12','2464','BA','PR','PEMNJS87090315M200','7229090715');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMARENA','GARCIA','MONICA GA','9','RG25','2510','C1','S1','CMGRMN73040209M900','7223521781');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','ROJAS','RUBEN','9','RG25','2510','C1','S1','LPRJRB52021115H900','7229147803');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PALACIOS','MORALES','PATRICIA','9','RG25','2510','C1','S1','PLMRPT73032515M301','7221737603');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','DURAN','KARINA','9','RG25','2510','C1','S1','GRDRKR87052015M400','7221624703');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVIRDE','GARCIA','ALDO','9','RG25','2510','C1','S1','ALGRAL70020815H000','7224748170');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','ESQUIVEL','ALONSO','5','RG12','2464','BA','PR','HRESLR64081015H700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ENRIQUEZ','PORCAYO','BERTHA','9','RG25','2510','C1','S1','ENPRBR62082215M500','7293259731');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CORONA','URIBE','ABISAI','5','RG12','2464','BA','PR','CRURAB94050315H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARMONA','MARTINEZ','ANGELICA','9','RG25','2510','C1','S1','CRMRAN68052015M000','7224402532');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','ORTIZ','OLIVIA ANG','5','RG12','2464','BA','PR','GNOROL66121115M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ENRIQUEZ','ENRIQUEZ','ARIADNA','9','RG25','2510','C1','S1','ENENAR96062615M700','7291857348');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ZUÑIGA','CRUZ','KATIA','9','RG25','2510','C1','S1','ZGCRKT99062509M900','7292888014');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ANGELES','TOLEDO','CATALINA','9','RG25','2510','C1','S1','ANTLCT84043015M900','7228954236');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CRUZ','VENTURA','MARGARITA','5','RG12','2464','BA','PR','CRVNMR59022015M000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANABRIA','MANCEBO','EMMANUEL','5','RG12','2464','BA','PR','SMNMEM96071715H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('oRTEGA','LUGO','MARCELA DOLOR','5','RG12','2464','BA','PR','ORLGMR79040715M000','7293604377');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHAVEZ','CONTRERAS','ANNEL','5','RG12','2464','BA','PR','CHCNAN75012915M700','7222448756');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARIBAY','AYALA','JUAN CARLOS','5','RG12','2464','BA','PR','GRAYJN88011415H100','7293311024');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LARA','RIVERA','GABRIEL','8','RG21','2536','C1','S1','LRRVGB64022815H500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','JIMENEZ','ANGEL A','5','RG12','2464','BA','PR','RDJMAN01071715H000','7221417478');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RIVERA','TORRES','JANET AZUCE','8','RG21','2536','C1','S1','RVTRJN95020715M500','7292262520');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','MARTINEZ','PASCUAL','5','RG12','2464','BA','PR','LNMRPS620051715H30','7225470725');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHACON','MEJIA','NALLELY','8','RG21','2536','C1','S1','CHMJNL89060515M800','7291270102');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','VAZQUEZ','BLANCA','8','RG21','2536','C1','S1','MJVZBL76113015M00','7228632205');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','HERNANDEZ','DIEGO AB','8','RG21','2536','C1','S1','TRHRDG01071215H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','PINEDA','EVELIN','8','RG21','2536','C1','S1','DZPNEV00011815M700','7292636970');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','VAZQUEZ','ANDRES DILA','8','RG21','2536','C1','S1','RYVZAN00031615H800','7223437545');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DE LA LUZ','SANCHEZ','VICTORI','8','RG21','2536','C1','S1','LZSNVC90072029M900','7227917553');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMPOS','HERNANDEZ','MARIA DE','5','RG12','2464','BA','PR','cmhrrs97040815m500','55613640926');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORALES','DIAZ','ISBAIREL','5','RG12','2464','BA','PR','MRBZIS8606115M500','7227095308');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','CAJERO','MARGARIT','5','RG12','2464','BA','PR','HRCJMR89123015M500','7291078721');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','HERNANDEZ','JUAN','5','RG12','2464','BA','PR','HRHRJN8104175H300','7224001640');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LEON','CARRASCO','JEREMIAS ET','5','RG12','2464','BA','PR','LNCRJR01100915H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','FLORES','MITZI ELIZ','5','RG12','2464','BA','PR','RMFLMT95071515M700','7291575770');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','GARCIA','CLAUDIA','5','RG12','2464','BA','PR','RMGRCL75051615M101','7224001640');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','RAMIREZ','MONSERRAT','5','RG12','2464','BA','PR','RMRMMN89122015M500','7222348291');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','ROSSANO','JESICA EL','5','RG12','2464','BA','PR','RMRSJS86081115M500','5613640926');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SUAREZ','PIÑA','CESAR VICENTE','5','RG12','2464','C3','S1','SRPICS96012215H000','7223453131');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','ROSSANO','JOSAFAT','5','RG12','2464','BA','PR','RMRSJS89100815H100','7227892141');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TORRES','FLORES','FIDEL','5','RG12','2464','C3','S1','TRFLFD82051115H500','7223459336');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','ROSSANO','SERGIO AL','5','RG12','2464','BA','PR','RMRSSR85013115H500','7291260712');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJI','GARCIA','DIEGO','5','RG12','2464','BA','PR','MJGRDG03032915H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','MONTES DE OCA','ARAC','5','RG12','2464','BA','PR','GMNAR75072415M000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','MONTES DE OCA','ARAC','5','RG12','2464','BA','PR','GMNAR75072415M001','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVAREZ','FABILA','HEIZEN VIR','6','RG17','2495','C1','S1','ALFBHZ88031315M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARMONA','GUADARRAMA','VALERI','6','RG17','2495','C1','S1','CRGDVL98081315M500','7221023966');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DELGADO','FABILA','ARTURO','6','RG17','2495','BA','S1','DLFBAR92010515H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DELGADO','FABILA','ARTURO','6','RG17','2495','BA','S1','DLFBAR92010515H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALCANTARA','PLATA','EVELYN','6','RG17','2495','C1','S1','ALPLEV96041915M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALBITER','GUTIERREZ','BETHSY','6','RG17','2495','C1','S1','ALGTBT92090915M100','7224097815');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ALVAREZ','DE LA ROSA','ISELA','6','RG17','2495','C1','S1','ALRSIS7206281M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BARRERA','MIRANDA','JOSE LUIS','6','RG17','2495','C1','S1','BRMRLS63041915H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','PONCE DE LEON','GABR','6','RG17','2495','C1','S1','BRPNGB86929315M800','7227019960');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMACHO','BERNAL','JAQUELINE','6','RG17','2495','C1','S1','CMBRJQ01092615M300','7292392374');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CAMPOS','AHUMADA','EMMANUEL','6','RG17','2495','C1','S1','CMAHEM81061015H100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DE JESUS','VALLEJO','MONICA','6','RG17','2495','C1','S1','JSVLMN77011715M300','7225016287');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DE LA ROSA','MORENO','JUDITH','6','RG17','2495','C1','S1','RSMRJD92082015M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','ALVA','MARTIN','6','RG17','2495','C1','S1','DZALMR63080315H000','7225818806');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','SOTENO','JESUS ANTONIO','6','RG17','2495','C1','S1','DZSTJS87075215H500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DOMINGUEZ','BUENO','GEORGINA','6','RG17','2495','C1','S1','DMBNGR01041812M500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESPINOSA','ESPINOSA','ANTONIO','6','RG17','2495','C1','S1','ESESAN96191215H900','7221758505');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FIGUEROA','HERNANDEZ','DANIEL','6','RG17','2495','C1','S1','FGHRDN96041415M700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GALINDO','MACEDO','DOLORES MA','6','RG17','2495','C1','S1','CMLCDL78110615M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','MACEDO','EUSEBIO','6','RG17','2495','C1','S1','GRMCES66061415H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','PATLAN','MARIO ANT','6','RG17','2495','C1','S1','GNPTMR64060215H900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','SANTANA','JAMES AL','6','RG17','2495','C1','S1','GNSNJN87081615H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','ZEPEDA','CARLOS EN','6','RG17','2495','C1','S1','GNZPCR97091415H600','7221299841');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','ZEPEDA','JOSE DE J','6','RG17','2495','C1','S1','GNZPJS96122415H600','7227553877');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUTIERREZ','AMIZCUA','SAIDA I','6','RG17','2495','C1','S1','GTAMSD760914M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUTIERREZ','DOMINGUEZ','JUAN','6','RG17','2495','C1','S1','GTDMJN92122315H500','7221947518');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LICEA','LOPEZ','MIRIAM','6','RG17','2495','C1','S1','LCLPMR95051815M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','MEDINA','ABRAHAM','6','RG17','2495','C1','S1','LPMDAB84100415H200','7222446633');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','HERRERA','NELLYANA','6','RG17','2495','C1','S1','MRHRNL77111430M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','ARCHUNDIA','GEORGINA','6','RG17','2495','C1','S1','MJARGR76061215M501','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MENDEZ','PEREDO','RAFAEL','6','RG17','2495','C1','S1','MNPRRF55022709H100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONROY','TERON','ALEJANDRA','6','RG17','2495','C1','S1','MNTRAL88081215M500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORALES','LOPEZ','OSCAR MIGUE','6','RG17','2495','C1','S1','MRLPOS97060115H600','7223607939');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ORTIZ','GALINDO','ALONDRA DEN','6','RG17','2495','C1','S1','ORGLAL02123015M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PEREA','SANTANA','BRYAN DANIE','6','RG17','2495','C1','S1','PRSNBR00062615H100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PLASCENCIA','PALOMERO','VICTO','6','RG17','2495','C1','S1','PLPLVC84030315H900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PLATA','MORALES','AMINTIA DEL','6','RG17','2495','C1','S1','PLMRAM74072215M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('QUIROZ','REBOLLAR','MARIA DEL','6','RG17','2495','C1','S1','QRRBCN84031115M700','7223834910');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','CASTILLO','ROSALIND','6','RG17','2495','C1','S1','RMCSRS61061409M500','7225567471');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','LOPEZ','MARIA EUGEN','6','RG17','2495','C1','S1','RMNGMR70071215M700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','NAVA','JOSE LUIS','6','RG17','2495','C1','S1','RMNVLS85120915H300','7221145294');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RIVERA','CAMACHO','MARIA ELIZ','6','RG17','2495','C1','S1','RVCEL00092315M500','7226105855');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RIVERA','CAMACHO','TANYA BANE','6','RG17','2495','C1','S1','RVCMTN96083015M200','7228400662');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','MARTINEZ','EVA','6','RG17','2495','C1','S1','RDMREV91052215M700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROJAS','DIAZ','ESTELA','6','RG17','2495','C1','S1','RJDZES74121615M500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SALAZAR','JENIFER','DANIELA','6','RG17','2495','C1','S1','XXSLJN92090509M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SALDAÑA','CALLEJAS','JOSE JUA','6','RG17','2495','C1','S1','SLCLJN99112615H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','FOGARTY','QUINTANA','6','RG17','2495','C1','S1','SNQNVR76010609M900','7224888972');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','TERRON','ESTEBAN','6','RG17','2495','C1','S1','SRTRES71122615H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOLANO','SANCHEZ','BRYAN BRET','6','RG17','2495','C1','S1','SLSNBR95042815H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOTO','BARRERA','VICTOR','6','RG17','2495','C1','S1','STBRVC65011015H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESTRADA','SOTO','SANDRA','6','RG17','2495','C1','S1','ESSTSN94042215M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOTO','ESTRADA','VICTOR ALFON','6','RG17','2495','C1','S1','STESVC88060815H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TAHUILAN','SERRANO','GABRIELA','6','RG17','2495','C1','S1','THSRGB73022115M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TEPICHIN','VAZQUEZ','BEATRIZ','6','RG17','2495','C1','S1','TPVZBT99090315M200','7227444878');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VARGAS','RANGEL','FRANCISCO','6','RG17','2495','C1','S1','BRRNFR74030515H100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','SERRANO','JOCELYN A','6','RG17','2495','C1','S1','VZSRJC99060415M600','5613296599');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORAN','BECERRIL','YESSICA SU','5','RG14','2471','BA','PR','MRMCYS90102215M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PONCE','RAMIREZ','JORGE','9','RG26','2532','C2','S1','PNRMJR000060415H50','7222474974');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','GARCIA','MARCELA','9','RG26','2532','C2','S1','RMGGMR79081915M901','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ABASTA','ESCOBEDO','GABRIELA','5','RG14','2471','C3','S1','ABESGB84120515M800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RAMIREZ','GARCIA','PATRICIA','9','RG26','2532','C3','S1','RMGRPT70081715M300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ARCHUNDIA','TEPICHIN','JUAN','5','RG14','2471','C3','S1','ARTPJN98052315H800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','MEJIA','EMILIO JUAN','9','RG26','2532','C2','S1','RYMJEM92031715H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','PONCE DE LEON','GABR','5','RG14','2471','C3','S1','BRPNGB86929315M800','7227019960');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('BERNAL','PONCE DE LEON','VERO','5','RG14','2471','C3','S1','BRPNVR83052015M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','HERNANEZ','IVONNE','9','RG26','2532','C4','S1','RBHRIV92012415M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARBAJAL','DOMINGUEZ','IRIS A','5','RG14','2471','C3','S1','CRDMIR89120715M800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CARRILLO','AYALA','JOSE ARMAN','5','RG14','2471','C3','S1','CRAYAR85022815H500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','ROMERO','ANGEL','9','RG26','2532','C2','S1','RBRMAN02073015H600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROBLES','ROMERO','BRAULIO','9','RG26','2532','C2','S1','RBRMBR00062315H800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CHAVEZ','GARIBAY','AURA CAROL','5','RG14','2471','C3','S1','CHCRARR0110115M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROCHA','LEON','DANIEL','9','RG26','2532','C4','S1','RCLND85062815H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DIAZ','CLIMACO','ADALID','5','RG14','2471','C3','S1','DZCLAD87090315M700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('RODRIGUEZ','GONZALEZ','KENIA','9','RG26','2532','C2','S1','RDGNJN68030609M800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESQUIVEL','MEJIA','MARIA ADRI','5','RG14','2471','C3','S1','ESMJAD85081515M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GALICIA','ORTEGA','ALAN ANDRE','5','RG14','2471','C3','S1','GLORAL98062215H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','ALONSO','DAVID ANDR','9','RG26','2532','C2','S1','SNALDV01112115H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GARCIA','CONSTANTINOLUIS','AL','5','RG14','2471','C3','S1','GRCNLS91050315H900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANCHEZ','VILCHIS','MA DE LOS','9','RG26','2532','C2','S1','SNVLMA59021115M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','CUAMATZI','JUAN CA','5','RG14','2471','C3','S1','GNCMJN74032615H700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','MEJIA','HERIBERTO','5','RG14','2471','C3','S1','GNMJHR79031615H400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','GARCIA','DAFNE JAFE','9','RG26','2532','C3','S1','SRGRDF89012115M100','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUADARRAMA','GASPAR','DIANA K','5','RG14','2471','C3','S1','GDGSDN03011015M800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SERRANO','GARCIA','JORDAO','9','RG26','2532','C2','S1','SRGRJR85112615H900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUERRERO','ALCANTARA','MIGUEL','5','RG14','2471','C3','S1','GRALMG83120515H300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOL','GARDUÑO','SERGIO ALEJAN','9','RG26','2532','C4','S1','SLGRSR99041015H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUTIERREZ','ENRIQUEZ','MARIA','5','RG14','2471','C3','S1','GTNRMR67020815M000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOLIS','GARCIA','NAYELY','9','RG26','2532','C3','S1','SLGRNNY91072715M90','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LINARES','BERNAL','ABIGAIL','5','RG14','2471','C3','S1','LNBRAB95041015M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('TOLEDO','VALLEJO','ERICK','9','RG26','2532','C3','S1','TLVLER93050715H500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','JUAREZ','DANIA','5','RG14','2471','C3','S1','LPJRDN02010315M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','SANCHEZ','CRISPIN','5','RG14','2471','C3','S1','LPSNCR94030315H700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VALDEZ','MONTES DE OCA','PABL','9','RG26','2532','BA','S1','VLMNPB92101215H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOPEZ','SANCHEZ','IVAN','5','RG14','2471','C3','S1','LPSNIV92111615H200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','GARCIA','CARLA FERNAN','5','RG14','2471','C3','S1','MJGRCR96081915M000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','LOPEZ','LUIS','5','RG14','2471','C3','S1','MJRPLS54102215H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','RUBIO','ANDREA KARELY','5','RG14','2471','C3','S1','MJRBAN96050915M700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEJIA','SANCHEZ','HUGO ISRAEL','5','RG14','2471','C3','S1','MJSNHG76101715H700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MORAN','BECERRIL','PAOLA GUAD','5','RG14','2471','C3','S1','MRBCPL99120615M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEZA','ARIZMENDI','PAVEL VLAD','5','RG14','2471','C3','S1','MZARPV74110915H800','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONRROY','MERCADO','GISELA','5','RG14','2471','C3','S1','MNMRGS75082009M300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONROY','VALLE','VELVET','5','RG14','2471','C3','S1','MNVLVL85081415M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('JIMENEZ','FERNANDEZ','MARTHA','2','RG05','2549','C3','S1','JMFRMR70062916M300','7222678340');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ZAMORA','ZPATA','IRENE VERONI','2','RG05','2549','C3','S1','ZMZPIR71020515M300','7221405625');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('HERNANDEZ','JIMENEZ','VALERIA','2','RG05','2549','C3','S1','HRJMVL00011015M100','7224607478');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MONDRAGON','RODRIGUEZ','ROSAM','2','RG05','2549','C3','S1','MNRDRS71081016M200','7221503046');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('CONDE','CAMILO','ANGELES JHOA','2','RG05','2549','C3','S1','CNCMAN01030615M400','7295030501');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SANABRIA','OLIVERA','MARIA JO','2','RG05','2549','C3','S1','SNOLMR01010715M300','7228633853');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MIRA','MANCILLA','ANGELICA RO','2','RG05','2549','C3','S1','MRMNAN90030715M200','7291157818');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('DOTOR','MARTINEZ','DANIELA SO','2','RG05','2549','C3','S1','DTMRDN02100415M000','7291463078');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GONZALEZ','MONDRAGON','CLARA','2','RG05','2549','C3','S1','GNMNCL96070215M100','7225623954');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LUNA','MONDRAGON','MERCEDES','2','RG05','2549','C3','S1','LNMR00092415M900','7224686326');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ROCHA','LEON','SANDRA','2','RG05','2549','C3','S1','RCLNSN93071815M200','7291002814');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MARTINEZ','LOPEZ','ERICK','2','RG05','2549','C3','S1','MRLPER88032525H600','7228435750');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('FLORES','ARZATE','IVONNE','2','RG05','2549','C3','S1','FLARIV80022615M400','7292968643');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','ZAMORA','JULIO CESAR','2','RG05','2549','C3','S1','RYZMJL80111915H000','7222348558');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ABURTO','MARTINEZ','ADAME-NEC','5','RG13','2467','C1','S1','ABMRAD84012130M601','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ACEVEDO','GOMEZ','NAYELI','5','RG13','2467','C1','S1','ACGMNNY01091715M70','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('ESPINOZA','GONZALEZ','GABRIEL','5','RG13','2467','C1','S1','ESGNGB81082316M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('GUILLEN','SALAS','KAREN AMAYR','5','RG13','2467','C1','S1','GLSLKR93011016M200','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOVERA','HERNANDEZ','ALMA ERI','5','RG13','2467','C1','S1','LVHRAL99020515M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('LOVERA','HERNANDEZ','ALICIA','5','RG13','2467','C1','S1','LVHRAL95070209M500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MEDINA','GARCES','JUAN DE DIO','5','RG13','2467','C1','S1','MDCRJN97030815H700','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('MENDEZ','BASTIDA','CINTHYA PA','5','RG13','2467','C1','S1','MNBSCN95122515M900','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PADUA','DIAZ','SUSANA MONSERR','5','RG13','2467','C1','S1','PDDZSS89021215M400','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PADUA','DIAZ','LUZ MARIELA','5','RG13','2467','C1','S1','PDDZEL86101815M600','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('PERFECTO','ESPINOZA','JESUS A','5','RG13','2467','C1','S1','PRESJS99080315H000','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('REYES','VAZQUEZ','MIRIAM BIAN','5','RG13','2467','C1','S1','RYVZMR99031915M300','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('SOTO','HERNANDEZ','KARINA','5','RG13','2467','C1','S1','STHRKR90022215M500','');
INSERT INTO datita (apellido_p,apellido_m,nombres,zona,rg,seccion,casilla,pos,clave_e,tel) VALUES ('VAZQUEZ','ROMERO','MARIA BLAN','5','RG13','2467','C1','S1','VZRMBL78081715M401','');
