-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 16:19:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema metepec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metepec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metepec` ;
USE `metepec` ;

-- -----------------------------------------------------
-- Table `metepec`.`promotores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metepec`.`promotores` (
  `id_promotores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_promotores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metepec`.`beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metepec`.`beneficiarios` (
  `id_beneficiario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NOT NULL,
  `vulnerable` TINYINT NULL DEFAULT NULL,
  `curp` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_identificacion` VARCHAR(20) NULL DEFAULT NULL,
  `numero_identificacion` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `whats` TINYINT NULL DEFAULT NULL,
  `fech_nacimiento` INT NULL DEFAULT NULL,
  `dir_calle` VARCHAR(45) NULL DEFAULT NULL,
  `dir_numero` VARCHAR(5) NULL DEFAULT NULL,
  `dir_numero_int` VARCHAR(5) NULL DEFAULT NULL,
  `id_colonia` VARCHAR(45) NULL DEFAULT NULL,
  `otra_colonia` VARCHAR(50) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `dir_referencia` VARCHAR(255) NULL DEFAULT NULL,
  `solicitud_basico` VARCHAR(255) NULL DEFAULT NULL,
  `parentezco` VARCHAR(100) NULL DEFAULT NULL,
  `id_promotores` INT NULL DEFAULT NULL,
  `id_auxiliar` INT NULL DEFAULT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  `id_medio_contacto` INT NULL DEFAULT NULL,
  `id_origenes` INT NULL DEFAULT NULL,
  `nivel` ENUM('1', '2', '3', '4', '5') NULL DEFAULT NULL,
  PRIMARY KEY (`id_beneficiario`),
  INDEX `fk_beneficiarios_empleados` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_beneficiario_auxiliar` (`id_auxiliar` ASC) VISIBLE,
  INDEX `fk_beneficiarios_origen` (`id_origenes` ASC) VISIBLE,
  INDEX `fk_beneficiario_medio` (`id_medio_contacto` ASC) VISIBLE,
  INDEX `fk_beneficiarios_promotores_idx` (`id_promotores` ASC) VISIBLE,
  CONSTRAINT `fk_beneficiarios_empleados`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `metepec`.`empleados` (`id_empleado`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_beneficiario_auxiliar`
    FOREIGN KEY (`id_auxiliar`)
    REFERENCES `metepec`.`auxiliares` (`id_auxiliar`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_beneficiarios_origen`
    FOREIGN KEY (`id_origenes`)
    REFERENCES `metepec`.`origenes` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_beneficiario_medio`
    FOREIGN KEY (`id_medio_contacto`)
    REFERENCES `metepec`.`medio_contacto` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_beneficiarios_promotores`
    FOREIGN KEY (`id_promotores`)
    REFERENCES `metepec`.`promotores` (`id_promotores`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
